# Generated by Django 6.0 on 2025-12-26 09:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
