from django.urls import path
from . import views
from .views import CustomPasswordResetView, CustomPasswordResetConfirmView

urlpatterns = [
    path('', views.home, name='home'),
    path('notes/', views.note_list, name='note_list'),
    path('note/<int:pk>/', views.note_detail, name='note_detail'),
    path('course/<int:course_id>/', views.note_list, name='notes_by_course'),
    path('topic/<int:topic_id>/', views.note_list, name='notes_by_topic'),
    path('note/create/', views.note_create, name='note_create'),
    path('note/<int:pk>/update/', views.note_update, name='note_update'),
    path('note/<int:pk>/delete/', views.note_delete, name='note_delete'),
    path('note/<int:pk>/summarize/', views.note_summarize, name='note_summarize'),
    path('note/<int:pk>/flashcards/', views.generate_flashcards, name='generate_flashcards'),
    path('note/<int:pk>/flashcards/view/', views.view_flashcards, name='view_flashcards'),
    path('note/<int:pk>/share/', views.share_note, name='share_note'),
    path('note/<int:pk>/share/remove/<int:user_id>/', views.unshare_note, name='unshare_note'),
    path('note/<int:pk>/comment/add/', views.add_comment, name='add_comment'),
    path('note/<int:pk>/comment/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    path('note/<int:pk>/export/pdf/', views.export_note_pdf, name='export_note_pdf'),
    path('note/<int:pk>/export/markdown/', views.export_note_markdown, name='export_note_markdown'),
    path('note/<int:pk>/voice/', views.voice_notes, name='voice_notes'),
    path('note/<int:pk>/voice/<int:voice_note_id>/delete/', views.delete_voice_note, name='delete_voice_note'),
    path('analytics/', views.analytics_dashboard, name='analytics_dashboard'),
    path('shared/', views.shared_notes_list, name='shared_notes_list'),
    path('signup/', views.signup, name='signup'),
    path('courses/', views.course_list, name='course_list'),
    path('course/new/', views.course_create, name='course_create'),
    path('course/<int:pk>/edit/', views.course_update, name='course_update'),
    path('course/<int:pk>/delete/', views.course_delete, name='course_delete'),
    path('topics/', views.topic_list, name='topic_list'),
    path('topic/new/', views.topic_create, name='topic_create'),
    path('topic/<int:pk>/edit/', views.topic_update, name='topic_update'),
    path('topic/<int:pk>/delete/', views.topic_delete, name='topic_delete'),
    path('profile/', views.profile, name='profile'),
    path('search/', views.search_results, name='search_results'),
    path('documents/', views.document_list, name='document_list'),
    path('documents/upload/', views.document_upload, name='document_upload'),
    path('documents/<int:pk>/', views.document_view, name='document_view'),
    path('documents/<int:pk>/delete/', views.document_delete, name='document_delete'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]
